// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIZNaCLwj0FHBUKLrLnVRBOaJDpLt4d9E',
    appId: '1:278107815726:web:2a3e6b2957d2dae59bc4bf',
    messagingSenderId: '278107815726',
    projectId: 'goyou-3ba1f',
    authDomain: 'goyou-3ba1f.firebaseapp.com',
    storageBucket: 'goyou-3ba1f.firebasestorage.app',
    measurementId: 'G-QHP5SD07F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9XsS1GAMgKYVjX_Psyim0SJvt3qH2LeA',
    appId: '1:278107815726:android:7840f62f73bba5949bc4bf',
    messagingSenderId: '278107815726',
    projectId: 'goyou-3ba1f',
    storageBucket: 'goyou-3ba1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb3UUxR6ILuHSH_kvCG0LP0g347FdSG78',
    appId: '1:278107815726:ios:78d861a06c27b7599bc4bf',
    messagingSenderId: '278107815726',
    projectId: 'goyou-3ba1f',
    storageBucket: 'goyou-3ba1f.firebasestorage.app',
    iosBundleId: 'com.example.goYou',
  );

}